### ISSUE TITLE
Double quotes and newlines rendering in Justification modals

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#10]
The modals on the quiz-grader route renders the following erroneously: 
- [x] double quotes as \\"
- [x] newlines as  \\n

In comparison, the question displayed to its left does render them properly. Check for differences along the chain the data followed.

This seems to happen at least in the justifications, likes received, and likes given modals.

**Comment by neverdue** [comment]
Do you see these errors when using the Easy Label Test DB or the actual DB from the class?
I have been using the Easy Label Test DB so I was not seeing this, how can I reproduce this error?

**Comment by profgrumpy** [comment]
yup you need to use a DB where the justifications are featuring " \ I saw a \n but I'm not 100% if it's a fluke from something the poster did or something more systematic.
On the plus side, single quotes are fine :) didn't try backticks though ;p

**Comment by neverdue** [comment]
Gotcha let me switch to a different database then and fix this!

**Comment by neverdue** [comment]
Okay so this seems to be the issue on the database side, for some students that have used a table in their justification, multiple \n are being stored in the justification table which renders as text

**Comment by neverdue** [comment]
I believe I have fixed this issue and I am pushing the commit for this fix. (4fbaa75e67c48fe55bed94c13aaa742e33c179d4)
If there are still issues with this (which I anticipate) then please reopen this issue!

**Comment by profgrumpy** [comment]
Not sure we should substitute the " or ' or \n directly, the issue is really how they got there. If they did, this means I messed up the unescaping at some level :) need to figure out where and fix that part. The problem with removing these things like this is that someone might actually want to have that " or that ' or that \n. For example, if the questions are about code, then these characters need to be still in the questions after the instructor enters it in the system and displayed as is to the students. Similarly, if a student want to say something like

- The \n at the end is not necessary for the string "hello\n"

then it needs to make it through to the DB and back again when visualized in the modals or anywhere in the system.

Let me know if I'm missing something here, if not, let's reopen this one otherwise I'll need to eliminate all traces of this brainfart of mine from the interwebs ;p

**Comment by profgrumpy** [comment]
re-opening to replace duplicate issue #26

**Comment by profgrumpy** [comment]
Did a manual inspection on the most recent DB and found proper occurrences of both.
Closing.
