### ISSUE TITLE
Access to "grades" for a quiz that has none

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#106]
If we try to click on the "grades" button for a quiz that has none yet, we get an internal server error.

**Comment by profgrumpy** [comment]
ok the above makes sense; only quizzes that have been added to a course are assigned to students so there is no point in showing a grades icon if the quiz has not been assigned to any course / students yet.

**Comment by dvitel** [comment]
fixed division by zero, pushed.
