### ISSUE TITLE
Quiz Solutions not displaying (internal server error)

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#107]
We create a quiz and, manually, set it to step 1. We have the student take it. We then, manually again, set it to step 2 and have the student retake it. When we set it to "show solutions" and try to open it again on the student's side, it gives us an internal server error

**Comment by dvitel** [comment]
There was a problem of referencing a key in empty dict - due to absence of data for step 3 in the quiz. Step 3 is not fully tested yet and is not planned to be used in prod.
