### ISSUE TITLE
Assigning a quiz to multiple courses

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#109]
If a quiz is already assigned to a given course and we try to assign it to another, a copy is created. This might be the desired behavior but we then have the issue of both copies being updated when we toggle the "deadline driven" checkbox. 
This is reported already in another issue but we need to check here that we do want to make automatically a copy of a quiz instead of warning the user that the quiz is already assigned to a course (and the user would have to make a copy of the quiz by hand in order to assign that copy to another course)

**Comment by dvitel** [comment]
Related to #108
