### ISSUE TITLE
Accessing quiz solutions

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#110]
From the student's UI we see a quiz that is in the "SOLUTIONS" status. On the instructor's side, it is set on "show answers" and the "deadline driven" checkbox is not checked. 
When the student clicks on the quiz to view the solutions, we get an error message that states "Step 1 of this quiz is not available"

**Comment by dvitel** [comment]
I fixed the conditions when the solutions view is rendered. No matter what is the attempt status, the solutions view will be available when it is set by the instructor. Meanwhile, we need to consider if we would like to have Step3 at all.
