### ISSUE TITLE
Compute "participation score" and "participation grade"

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#12]
We want to encourage students to use likes, especially on worthy justifications.

How do we translate the number of likes a student has given in a quiz into a  "participation grade"?
 
Idea - Taking into account that if student gives more than 50% (percentage based on MaxLikes, see above) of all encountered justifications a like, they get diminishing returns.

**Comment by neverdue** [comment]
So basically if the max likes for a quiz is 39
50% of that is 19.5 so let's say we ceil the value to 20
Then if student1 gives 24 likes and student2 gives 5 likes
How do we decide the participation grade? @profgrumpy

**Comment by profgrumpy** [comment]
We will have a way to display to the student whether or not they are in the "green" to get their participation points or not. To determine this, we can target 20 likes and allow them a margin below that but not above. E.g., 20 likes is the ideal target, 20% the margin, so the students would get full participation points if they are between [16-20] likes given on this quiz. If they go above, their likes are worth less and their participation points go away.

**Comment by neverdue** [comment]
That makes sense, working on this feature now!

**Comment by neverdue** [comment]
Made a commit for this (366b0d1973bbbd6f48a44bb75285b4eb5de42aa9)

**Comment by profgrumpy** [comment]
Let's make this tunable from the grading page as part of this issue or, if you prefer, let's open a separate issue. Up to you.

**Comment by profgrumpy** [comment]
Closed pending the new test scripts
