### ISSUE TITLE
Editing a distractor in HTML mode prevents us from submitting it

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#120]
Create a question, then add a distractor to it. If the edit mode in the UI is HTML for the distractor, then clicking the submit button gets us back to the front page and the distractor has not been added. 
It works fine if we are editing the distractor's text in WYSIWIG mode instead.

**Comment by dvitel** [comment]
Summernote (old and new versions) did not sync main input to codeview input it renders. I added callback on each code-view update to set main input (which is submitted). Alternative solutions is to update main input on submit: https://stackoverflow.com/questions/43745941/summernote-wysiwyg-editor-save-in-codeview-not-working-js-jquery
Should be closed after merge and testing...
