### ISSUE TITLE
Some UI buttons for text edit boxes not responding

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#121]
The buttons available for all the text edit boxes are not working properly. If a button should trigger a dropdown of any sort, it does not anymore: e.g. click on the A button to change the color of the font and the color picker does not show

**Comment by dvitel** [comment]
Summernote expected bootstrap 4 while we had 5. An update to v0.8.20 from CDN did not help and they did not have newer version with other bugfixes (https://github.com/summernote/summernote/issues/4170). I compiled dist from their source (master branch) and added it to the site as static resources.

**Comment by dvitel** [comment]
Should be merged to master and tested one more time before close...

**Comment by profgrumpy** [comment]
seems to be working, closing issue
