### ISSUE TITLE
Compartimentalisation of Questions

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#127]
As an instructor, we can see all of the questions we authored as well as those authored by others. We need to isolate instructors from one another, best way might be to have a flag on the page that allows to list "only my questions" and show an author field for each question. If this is possible without changing the DB schema, let's talk. If not, let's hardcode the isolation as an option easily changeable (and documented on the wiki on here)

**Comment by dvitel** [comment]
I added a dropdown to pick questions from an instructor. The design refactoring we are going to discuss the next week.
