### ISSUE TITLE
Balancing grade components in quiz-grader page

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#13]
On the quiz-grader page, we need a way to balance the grades received for the following: 
- justifications grade
- correctness of initial responses
- correctness of revised responses
- participation grade

Typically a single question is on 1 pt for pre-correctness and 1pt for post-correctness but 3 points for justifying the 3 alternatives that were not selected. We should be able to tune on the page the weight for each of the 4 grade components so as to recompute all the grades on the page (and for the CSV). 

The weight for each grade component should be saved in the DB as part of the Quiz model.

**Comment by profgrumpy** [comment]
See also Issue #15

**Comment by neverdue** [comment]
Added feature for:

1. correctness of initial responses
2. correctness of revised responses

Commit: (5a08eeb)

**Comment by neverdue** [comment]
Added feature for:

3. justifications grade
4. participation grade

Commit: (36e3741)

**Comment by profgrumpy** [comment]
See discord message 4/1/2022. This also apply to the weight for each grade component see issue #15 

For stuff like this, we might want to use a fetch request then reload the page from the JS in the page itself. This would allow the requests to be also handled as routes_mcq aka as part of the REST API since they would only change the weight / limiting factor in the model and then our page would reload / recompute what it needs once the fetch request has completed successfully.

**Comment by profgrumpy** [comment]
Closed pending the new test scripts
