### ISSUE TITLE
Back button while in step 2

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#131]
I had one case where a student while doing step 2, accidentally pressed the browser 'back' button and went to the previous webpage. But once she reentered the quiz, the justifications of other students were not displaying on her screen. So, she could not press the like button and was unable to proceed.

**Comment by profgrumpy** [comment]
Student should have been able to proceed without assigning likes, she would just not have received credit for participation.

**Comment by dvitel** [comment]
Related to #134 The problem was in incorrect computation of justification map on page refresh - keys should be alternative_ids in inner map, not distractors. Fixed this in the recent commit.
