### ISSUE TITLE
Changing user password fails

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#132]
This happens when logged as both an instructor and an admin: 
when trying to reset a user password we get:
There was a problem updating the user's Password: TypeError: Failed to fetch"

**Comment by profgrumpy** [comment]
@dvitel if you have to look into the url_for function, try for a solution that still allows us to run easily things locally without the need for an SSL certificate

**Comment by dvitel** [comment]
I found the solution to change **proxy_redirect** in nginx config:
```
proxy_redirect http:// $scheme://; 
```
This will rewrite the Location header to the scheme of request but I need to check template rendering for url_for

**Comment by dvitel** [comment]
I've just made this change on production and tested the password change under your account - it works. I assume the issue with Location header is fixed. I've checked how url_for work in templates - for templates it always renders relative URIs - so no issue with the protocol there. It is only on redirects on the backend and we fixed this in a recent commit.
