### ISSUE TITLE
Copying a step 1 quiz blocks the new one in that step

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#135]
if we copy a quiz that is in step 1 it is locked in step 1 and cannot be hidden or moved to show solutions

**Comment by dvitel** [comment]
It happens due to the wrong id forming in the template. Elements with id "status12" could refer to the status of quiz 2 in course 1 or to quiz 12 which is not assigned to any course. Fixing this ambiguity with additional separators. I will also check other templates for similar errors.

**Comment by dvitel** [comment]
Fixed in the commit above. Refactored <script> tags to have only one defined function instead of one per quiz. Flashland as toast with 5s timeout.
