### ISSUE TITLE
Multislider issues when configuring percentage worth of each step + justifications + participation

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#136]
In the quiz edit (and gradebook potentially) the multislider to configure the % of grade for each step can get stuck with multiple labels on the rightmost side

**Comment by dvitel** [comment]
It happens in Chrome browser. Mozilla works fine. Need to fix z order of handles

**Comment by dvitel** [comment]
Removed z-indexing. Instead I do sorting of handles on handle move to figure out constraints. Did testing and it seems that bug was fixed.
