### ISSUE TITLE
Basing test scripts on CSV comparisons

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#14]
Modify the Easy Labels Tests scripts so that they end up downloading the CSV and comparing it (diff?) with a hand-verified CSV that we already double checked to have the exact correct results.

**Comment by profgrumpy** [comment]
See commits 
- 7f37b78214baa0cb4dcfbc7c878ae1c31f27d960
- d76ba63bd6ac33509635fc45e2c9bbed51085705

**Comment by profgrumpy** [comment]
Reopen / Update

Making it so that 4 students are used to check the boundary of acceptable number of likes to get participation credit.
For instance, if the acceptable range is [8:10] then we would have a student use 7 likes, another 8, another 10, and the last one 11.
Two of those would get credit, the other two would not but that would allow us to guarantee the right range is enforced.

**Comment by profgrumpy** [comment]
Update again based on issue #45 adding that percentage column

**Comment by profgrumpy** [comment]
update based on issue #46 to test the new configurations options

**Comment by neverdue** [comment]
Need to test the LF implementation for the PT

**Comment by profgrumpy** [comment]
Suggestion: add a test specifically meant to detect whether issue #10 can be now closed or not

**Comment by profgrumpy** [comment]
To add to the above: 
The problem with testing with bash scripts is that we do not get to input " in the summernote editor so we already \" it in the script. Plus it adds another layer of language escaping for strings... Maybe save a .sqlite file with a sample of questions / justifications / distractors that feature all the escape character issues and use that for testing, in addition to the bash scripts, by visually inspecting the result.

**Comment by profgrumpy** [comment]
check also for backslashes \, \\, \\\ and even HTML tags. Again, these might have to be injected through SummerNote by hand in order to actually test in realistic conditions.

**Comment by profgrumpy** [comment]
Closing since we just closed #10 and the only way we have to test this right now is visually since adding \" in the bash testing scripts would add a layer of indirection...
