### ISSUE TITLE
Quiz-grader should allow to tune Limiting Factor

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#15]
The LimitingFactor should be modifiable on the grading page. E.g., "you can only like maximum 50% of the justifications you see" 
This value should also be saved in the Quiz model and in the DB, just like the grade components from issue #13

**Comment by neverdue** [comment]
So we are storing the max likes for a quiz in the DB as one of the fields for the Quiz table?
So on the quiz grader page for that quiz if we change the amount let's say from 50% to 25% then it needs to be updated in the database as well?

**Comment by neverdue** [comment]
Also in that context, we are trying to change the limiting factor right?
In the formula for the justification score we have
like_scores[grades[i].student_id] += ( Likes(grades[j], grades[i]) * min( ( (MaxLikes * LimitingFactor) / likes_by_g ), 1 ) )
So this "you can only like maximum 50% of the justifications you see" is talking about the LimitingFactor being 0.5 right?

**Comment by neverdue** [comment]
Here's the commit for it (abe4c12383fac012830f0e8d75c7bca24d129c69)

**Comment by profgrumpy** [comment]
If we click "submit" while the selection box is on blank, it causes an internal server error

**Comment by profgrumpy** [comment]
Suggestion: the route you added to allow to POST the modified limitingFactor is /add/<qid>
I would suggest using instead something like /quizzes/<qid>/limitingFactor/<int:lim> to routes_mcq.py instead and make sure it works with a POST form data or with a POST of a json object. It's not really a full page but more a part of the REST API.

**Comment by profgrumpy** [comment]
Last one I need to apologize for; since I initially used "maxLikes" in this issue's description, the text on the quiz grader page and the names of variables / methods in your commits are also using maxLikes instead of limitingFactor. Could you clean that up when you get a chance? The new field you added to the model is already named limiting_factor so that's perfect. Sorry again about the confusion!

**Comment by neverdue** [comment]
Done! (98cd01a3a7a97d3a6c74d3a47117514630b8e20e)

**Comment by profgrumpy** [comment]
See discord message 4/1/2022. This also apply to the weight for each grade component see issue #13 

For stuff like this, we might want to use a fetch request then reload the page from the JS in the page itself. This would allow the requests to be also handled as routes_mcq aka as part of the REST API since they would only change the weight / limiting factor in the model and then our page would reload / recompute what it needs once the fetch request has completed successfully.

**Comment by profgrumpy** [comment]
Closed pending the new test scripts, we are going to also add a new issue for making sure that the select dropboxes are pre-selected with the percentages actually in the models when we load the page.
