### ISSUE TITLE
"Too many Likes" warning & participation score / grade display

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#17]
During step 2 in student.html, we need to have a way to warn the student when their number of likes is such that the value of each of their likes will be decremented. A warning popup could work but I think it might be better to have this information displayed somewhere in the page with a warning once we reach the maximal number of recommended likes.

This could be wrapped up together with displaying the current user's participation score / grade for the quiz.

**Comment by neverdue** [comment]
Here's the commit for this (9c5d77e)

Still needs more refinement!

**Comment by profgrumpy** [comment]
Changes before closing: 
- [ ] Keeping progress bar visible as we scroll through questions
- [ ] Completion of the progress bar should correspond to reaching the max number of allowed likes, not the absolute max number of likes that may be given in this quiz
- [ ] When going over this max, notify the user; e.g., bar turns red instead of green, message flashed or written next to or inside the bar...

**Comment by neverdue** [comment]
Pushed a commit for this! (2e5beec)
