### ISSUE TITLE
Ensure that we do not add a quiz question to a quiz if it does not have distractors

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#20]
In quiz-question-selector-2, if we add to a quiz a quiz question that doesn't feature any distractors (maybe even if it does but we didn't select any) then we get a nice crash

**Comment by neverdue** [comment]
Fixed issue, pushing commit now!

**Comment by profgrumpy** [comment]
i would also check on the route side of things. We can prevent the html page from sending a bad request, but someone can still craft a request to hit the REST URLs so we need to always double lock things; on the page, mostly for convenience, and on the server-side.

**Comment by profgrumpy** [comment]
The following methods might be the server-side ones you want to look at: 
- [ ] put_quizzes in routes_mcq.py need to double check on this one
- [ ] quiz_question_selector_3 in routes_pages.py should definitively be able to tell if we receive a QuizQuestion to add to a quiz with no distractors

**Comment by profgrumpy** [comment]
Also, quick question; in evopie/templates/quiz-question-selector-2.html you check the URL to determine whether or not there are distractors specified, why not just measure the length of checked_distractors?

**Comment by profgrumpy** [comment]
The browser-side prevents adding such a question by requiring that we select at least one distractor. 
It's good enough for now since, later on, we might want to temporarily create a question without any distractors and let these be added progressively by students or instructors.
