### ISSUE TITLE
Feature - Deadlines management and enforcement

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#21]
Add ability for instructor to set deadlines when releasing a quiz;
- [ ] DL0 is availability
- [ ] DL1 is for completing step1
- [ ] DL2, for completing step2
- [ ] DL3 is for availability of answers
- [ ] DL4 is for when quiz should be re-hidden.

Update the quizzes/x/take route so as to enforce DL0, DL1, & DL2. Flash back, from flask or JS fetch/ajax, appropriate messages back.

For now, we should not handle students trying to take step1 while step2 is not over but, in the future, this might be something to consider adding. Same for not allowing students to see solutions if they didn't participate yet to step1 and step2. In these scenarios, we should mark the student attempt as "late" or something. Another further option would be to prompt students for justification and invite them to get in touch with their instructor.

**Comment by profgrumpy** [comment]
see also issue #22

**Comment by neverdue** [comment]
@dvitel Can you confirm if the issue description needs to be updated? @profgrumpy mentioned, "Update the quizzes/x/take route so as to enforce DL0, DL1, & DL2." However, I think we don't use quizzes/quizid/take anymore and instead we use students/quizid ?

**Comment by neverdue** [comment]
Update: Need to implement a better solution so that the deadlines can replace the mechanism of the instructor having to switch the status of the quiz.
