### ISSUE TITLE
Verify that quizzes / questions / distractors cannot be modified once quiz released

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#22]
Once quiz released, its QuizQuestion should not be editable. Same for the corresponding Questions and their Distractors.

We are able to edit a question via question-editor but not its distractors when the quiz is in step 2. Both should be forbidden at that point though.

**Comment by profgrumpy** [comment]
This one was originally in issue #19 but fits here:
-[ ] quiz-editor should flash back a message when attempting to modify a deployed quiz and getting a 403

**Comment by neverdue** [comment]
Made it so that if we try to edit a quiz whose status is anything other than HIDDEN then it flashes a text that the quiz is not editable at this time and takes the user back to the hame page. Pushing the commit now! (82698ce171c5fc3a4c313d8175a43a483bfceb1d)

**Comment by profgrumpy** [comment]
awesome, we also need to make sure that the route to PUT a modification to the quiz is protected. That will be in routes_mcq.py
For now, I guess the following would have to be fixed but there might be more:
- [ ] put_question
- [ ] delete_question
- [ ] put_distractor
- [ ] delete_distractor
- [ ] delete_quiz_questions
- [ ] put_quiz_questions
- [ ] delete_quizzes
- [ ] put_quizzes

Take a look and comment back on here if not all of these should be modified, or even if you found others that should. I just made the above-list quickly by browsing the code.

**Comment by profgrumpy** [comment]
see also issue #21
