### ISSUE TITLE
Verify that all existing flash responses are actually displaying more than just some JSON

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#24]
- [x] quiz-editor same thing when saying "DB updated" it should flash a proper message instead of just flashing the JSON

**Comment by profgrumpy** [comment]
Looks like the file potentially doing this are the ones where we sendToFlashLand the body of a JSON response. 
Search for "flash" in the following: 
- [ ] quiz-editor.html
- [ ] quizzes-browser.html
- [ ] student.html

**Comment by neverdue** [comment]
Done! https://github.com/cereal-lab/EvoPIE/tree/24-verify-that-all-existing-flash-responses-are-actually-displaying-more-than-just-some-json
