### ISSUE TITLE
Add number of likes received

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#30]
Both in the modals from quizGrader for;

- The "grades for justification given"
- The "likes received"
Both modals should show the justifications that we talking about + the number of likes each of them received. This should make it easier for an instructor to double check what were the highly-liked justifications for each student.

**Comment by neverdue** [comment]
Added a commit for this feature (009065b31ee1b47838ab60c2c3f57344aa57977e)
