### ISSUE TITLE
Incremental grading

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#31]
Quiz grader is loading all grades up front which can be quite time consuming with a non-minimal number of users.

- [x] Make sure that, on page load, we only query the data base to get the minimal amount of information and leave the grade as ' - '
- [x] Add a way to recalculate the participation grades column, trigger it anytime we change the limiting factor as well 
- [x] Add a way to recalculate the justification grades (this one should be the time intensive one)
- [x] Add a way to recalculate the total grade every time we adjust the weights.

**Comment by profgrumpy** [comment]
I'm starting to think that even reloading one of the 4 modals, let alone an entire column, will be still particularly time intensive.
We might have to use those to let the users know that they need to be patient even if we break down the different loadings;
https://getbootstrap.com/docs/4.2/components/spinners/

**Comment by neverdue** [comment]
Made a commit for this in the enhancedGrading branch (e7f5e87)

**Comment by profgrumpy** [comment]
@neverdue Check out the server side processing mode for the data tables plugin at https://datatables.net/manual/data/

**Comment by neverdue** [comment]
Pushed a commit to fix this (9cef9d6)

**Comment by neverdue** [comment]
Fixed a minor issue that caused problems with csv (d4f85ab)

**Comment by profgrumpy** [comment]
Just need to test out thoroughly and do the pull request for this one
