### ISSUE TITLE
Displaying / hiding the justifications from peers in step 2 and tuning the number shown

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#34]
We have a hard coded maximum of 3 justifications being displayed right now: 
- [x] Allow this to be configured in the Quiz editor
- [x] Save the value in the Quiz model
- [x] Allow the justifications to be collapsed in the step 2 student interface for when we have many of them. Maybe even just pre-collapse them if > 3 or something like that

**Comment by profgrumpy** [comment]
We might want to collapse all peers' justifications by default and allow students to either not look at them at all (we need to track this down in the model of the attempt) or allow them to consult them and apply likes.

This might allow to identify to what degree students are interested in peer instruction at all, and then characterize the performance profiles of students who are or are not.

**Comment by profgrumpy** [comment]
To collapse, use a surrounding div maybe with the bootstrap classes, nothing more involved than that for the first shot at it. The tracking of who viewed the justifications (from the above comment) should be a new feature down the road. Please open it as such when closing this one (anyone who closes it).

**Comment by neverdue** [comment]
Pushed a commit for this (c5c6634)
