### ISSUE TITLE
Keep partial selections saved before submit

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#35]
If we close a quiz tab before to submit, all selections are lost. This makes it awkward for students to come back after thinking things through and have to re-enter their justifications + select answers again. This is even messier due to the shuffling of answers.

On selection of an alternative or unfocus of a justification editor, save to the model the student submission but mark it as "PENDING" somewhere. While the submission shows pending, students are able to modify it. When using submit, the pending status is removed thus preventing students from resubmitting.

**Comment by profgrumpy** [comment]
This might link to another issue (to be opened by @neverdue); we want to make it so that re-opening the page provides the student with the same selection of shuffling of alternatives, and also justifications. Making the process deterministic is what will allow to both prevent justifications-sampling and allow to record the selections made among the alternatives in both step1 and step2.

**Comment by profgrumpy** [comment]
see also issue #40

**Comment by profgrumpy** [comment]
alternatively to saving in models, use cookies

**Comment by dvitel** [comment]
we have to store written justifications in db because of cookie size constraint and the size we cannot predict. So it makes sense to save state in db for all: selected options, justifications, shuffling.

**Comment by dvitel** [comment]
Done this through db. QuizAttempt has alternatives column. Also, now endpoints expect initial and revised responses not in form of map of question:distractor, but in form of quesion:alternative - where alternative is position from alternatives for question - this level of indirection provides additional protection from leaks of correct answers to html on step1, step2 rendering. But at same time it makes current Extensive tests unusable - therefore it makes sense to work on flask cli tests as I started for quiz simulation - to fully migrate tests to python and remove testing folder
