### ISSUE TITLE
Duplicates of Liked Justifications Listed in "Likes Received" modal

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#4]
In the grading page, the likes received modal is showing duplicates when using the testing/Easy Labels Tests. This might indicate that the corresponding query should do a group by. While the number of likes is correct. we should not list the same justification multiple times in the modal because it was liked several times.

**Comment by profgrumpy** [comment]
If you want to reproduce this bug:
```bash
flask DB-reboot 
cd testing/Easy\ Labels\ Tests/
./setup.sh
./step1.sh
./step2.sh
```

**Comment by neverdue** [comment]
Fixed this issue, pushed the commit to the grading branch!
