### ISSUE TITLE
Verify layout of modals

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#43]
Current tests are using very short justifications / stems / alternatives.
Try on real DB to ensure the layouts are all readable with more data / structured data such as code fragments.

**Comment by profgrumpy** [comment]
The layout for the quiz grader is already "pouring out" on the right hand side of the data table layout.

**Comment by profgrumpy** [comment]
see issue #48 to help with this

**Comment by profgrumpy** [comment]
Adjustments needed so far: 
- [ ] Almost all modals should be larger if they are to display alternatives / questions / justifications
- [ ] All tables showing numbers like a number of likes for instance, should be tight around the number in terms of width so as to leave most room for the alternatives / questions / justifications
- [ ] The collapsible headers of the "number of likes" modal (and many others) are button, as per the accordion widget. Unfortunately, this breaks the formatting of any question that is multi-lines. Let's consider another representation

**Comment by neverdue** [comment]
Pushed a commit for this (c0a961e)

**Comment by neverdue** [comment]
Pushed a commit for fixing the likes given / likes received -> text centered to text-start (2b82915)
