### ISSUE TITLE
Enable detailed configuration of justifications grading 

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#46]
The maximal grade for justifications is hardcoded to 10. E.g., routes_pages.py line 548 in bc6039890b54313f52c7c0fc402e5e5692573d57
Depending on which quartile students fall into, they get a variable amount of points: 
- 1st quartile gets 1 pt
- 2nd quartile gets 3 pts
- 3rd quartile gets 5 pts
- 4th quartile gets 10

Instructors might want to change the point rewards for each quartile, which would in turn make the maximal justification grade variable. It should therefore be pulled from the model and we should have a UI to tune these values in the quiz editor and quiz grader.

**Comment by profgrumpy** [comment]
Are quartiles hardcoded to 25% / 50% / 75%?

**Comment by profgrumpy** [comment]
confirmed.

**Comment by neverdue** [comment]
Pushed a commit for this (df99149)
