### ISSUE TITLE
Document how justifications and participation are graded

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#52]
Since we had a fun time the other day trying to figure out the role of limiting factor and participation threshold, could you please dump some notes that summarize the consensus we reached (and the implementation ;p) on a wiki page for EvoPIE?
[here is the link](https://github.com/cereal-lab/EvoPIE/wiki/Computing-students'-grades)

**Comment by profgrumpy** [comment]
I took a stab at it, @neverdue please double check that this is 100% in line with your implementation.

**Comment by neverdue** [comment]
Made the changes, closing now
