### ISSUE TITLE
DB Migration scripts

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#54]
- [ ] Update the migration script in deployments/2022-spring-COP2512-alessio so that we can bring that data into the latest version of the master branch.
- [ ] Adapt @neverdue 's migration script used to update COP2512.S22 to the new schema, in order to convert the questions (and only the questions) from COP2513.F21 to a new COP2513.F22.

NOTE - migrating over the questions means actually migrating over the Distractors, Questions, QuizQuestions, Quizzes and the relations between them.

**Comment by drpventura** [comment]
Here's an automigration solution: https://alembic.sqlalchemy.org/en/latest/autogenerate.html
