### ISSUE TITLE
Ghost Participation Threshold widgets still get even listeners assigned to them :)

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#56]
We are still trying to slap an event listener on Participation Threshold even though it is no longer a widget that the user may change. 
Occurs in both quiz-editor and quiz-grader (to verify)

**Comment by profgrumpy** [comment]
mmm no longer sure that's the issue at hand here but the bug is 100% reproducible deterministically by loading the quiz-editor page, just check out the JS console.

**Comment by neverdue** [comment]
Made a commit to remove that listener (aa81f0b)
