### ISSUE TITLE
Deleting question in quiz editor

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#57]
Does not work anymore, we are using xhr though, maybe time to update this to a fetch request?

**Comment by profgrumpy** [comment]
NOTE - the test that revealed that bug involved having the same question added twice to a quiz; once when it had only 1 distractor, then again after adding another distractor
Before to go any further, verify that this is not a side effect of having multiple times the same question in a quiz. If so, we need to prevent that both from the UI and in the REST API.

**Comment by profgrumpy** [comment]
Nope... 
confirmed on a vanilla setup with different questions in a quiz.

**Comment by profgrumpy** [comment]
ok need help figuring out how to step through the JS embedded in the page with VSCode. Assuming the console errors from issue #56 are also causing the problem, these are not allowing me to zero-in on any part of the code via the developer tools...

**Comment by neverdue** [comment]
Just added a commit for issue #56 (aa81f0b)

**Comment by neverdue** [comment]
I think this is the issue here:

<a  href='#' onClick="removeQuizQuestion({{quiz}},{{qq.id}})" type="button" class="">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                </svg>
            </a>

I think we might be getting the error because we are passing the quiz as one of the arguments, not sure if that is being serialized

**Comment by profgrumpy** [comment]
You might be onto something there; I tried quiz | tojson and it gave me an internal server error explaining that the type quiz was not JSON serializable.

**Comment by profgrumpy** [comment]
The above commit might fix the issue... we need to test this thoroughly to make sure that the problem is gone no matter what ends up in justifications / title / stem / answer / ...

**Comment by profgrumpy** [comment]
Added justification column in distractor table as part of COP2512.S22 DB migration script so that we could test on real DB. It worked. Made sure both Easy Label Tests and Extensive Tests worked. 
Closing for now until we find what's wrong and not obvious right now.
