### ISSUE TITLE
Extensive tests return 405 Method not allowed

### ISSUE THREAD

**Issue by dvitel** [cereal-lab/EvoPIE#62]
After merge #61  it happen that extensive tests are not working. Obtained diff file:

```diff
1,4c1,20
< <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
< <title>405 Method Not Allowed</title>
< <h1>Method Not Allowed</h1>
< <p>The method is not allowed for the requested URL.</p>
---
> Last Name,First Name,Email,Initial Score,Revised Score,Grade for Justifications,Grade for Participation,Likes Given,Likes Received,Total Score,Final Percentage
> 8,BB,student7@usf.edu,2,2,5,1,19,0,2.2 / 5.1,43.1%
...
```
Problems:
https://github.com/cereal-lab/EvoPIE/blob/4fe1297d9837f7f9c6aa0e9e2a0cb0bd53030a33/evopie/routes_auth.py#L50-L52
and 
https://github.com/cereal-lab/EvoPIE/blob/4fe1297d9837f7f9c6aa0e9e2a0cb0bd53030a33/evopie/routes_pages.py#L787
have POST method, not specified in CURL in 
https://github.com/cereal-lab/EvoPIE/blob/4fe1297d9837f7f9c6aa0e9e2a0cb0bd53030a33/testing/Extensive%20Test/TestLib.sh#L53-L55

Also, after merge in order to complete file download, 
additional request to endpoint /grades/{{ quiz.id }}/justificationGrade is necessary
https://github.com/cereal-lab/EvoPIE/blob/4fe1297d9837f7f9c6aa0e9e2a0cb0bd53030a33/evopie/templates/quiz-grader.html#L275-L320

**Comment by dvitel** [comment]
I did fix of TestLib.sh https://github.com/cereal-lab/EvoPIE/commit/8912c71ff23e90efcada373c9322a2742b01d67c
Now test returns data but different from expected - please see commit details.

**Comment by profgrumpy** [comment]
@dvitel could you please apply the same fix to the "Easy labels" folder in tests as well?

**Comment by dvitel** [comment]
Done "Easy labels" and merge https://github.com/cereal-lab/EvoPIE/commit/0c5b1106bde8423e70554b953a90daa9eab24102
