### ISSUE TITLE
Freeze versions in pipfile based on committed pipfile.lock

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#65]
We have been having A LOT of issues when setting up Dmytro for work this summer. Using the latest version of every dependency is not an option since backward compatibility is not always a priority in said libraries.
Using pipenv sync allows to reliably replicate a working environment so we are going to apply the same version numbers to the pipfile. The goal is that regenerating from scratch using only the pipfile should give us a working environment.

**Comment by profgrumpy** [comment]
See reference doc at 
https://pipenv-fork.readthedocs.io/en/latest/basics.html

**Comment by profgrumpy** [comment]
Example of the problems that led us to this: 
since version 3.1.0 jinja2 Markup needs to be imported from MarkupSafe, see https://jinja.palletsprojects.com/en/3.1.x/changes/ for details.

**Comment by profgrumpy** [comment]
@drpventura when you set up your environment, please try to set it up without the .lock file and only doing a pipenv update based on the pipfile itself. That will be an opportunity for us to test that the environment can be build from scratch.

**Comment by profgrumpy** [comment]
Tested with Phil's setup, worked, closing.

**Comment by drpventura** [comment]
Based on https://stackoverflow.com/a/46303305, it appears that Pipfile.lock should exist in the repo.  I will commit the changes.
