### ISSUE TITLE
quiz-grader no longer updates weights

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#66]
Change weights, go back to quiz-browser, come back to quiz; the weights are back to original values. Confirmed by inspecting the DB.

The following methods in quiz-grader.html try to update the innerHTML of an element that no longer exists: 
- [ ] changeInitialScoreWeight
- [ ] changeRevisedScoreWeight
- [ ] changeJustificationGradeWeight
- [ ] changeParticipationGradeWeight
This should cause the extended tests' download-gradebook test to fail.

**Comment by profgrumpy** [comment]
At this point, it's possible the table update mechanism needs to be replaced by something in the lines of:
https://datatables.net/forums/discussion/67415/dynamic-datatable-populate-from-a-fetch-api

**Comment by drpventura** [comment]
The elements noted in the issue description do in fact exist on the page.  Right now the culprit appears to be the fact that lines 110 - 116 are commented out.  These lines add the functions as event listeners.  One question is about the async Javascript function named refresh (lines 226 - 237) which seems to all the various change functions.  However, it doesn't appear to be hooked up to anything.

**Comment by drpventura** [comment]
Added refresh as event listener for the "(Re)compute All Grades based on weight below" button.
Did not uncomment event listener lines 110-116 as it is believed that the more "global" approach above is needed to ensure scores add to 100%.
Inspection of database indicates that weights are updated

**Comment by profgrumpy** [comment]
Do you mind mentioning the issue number with syntax "issue #xyz" in the commit message so that it links your relevant commits right here too?

**Comment by drpventura** [comment]
Fields in the database are updated properly.
