### ISSUE TITLE
Extensive Tests not working

### ISSUE THREAD

**Issue by drpventura** [cereal-lab/EvoPIE#69]
On checkout of master, the Extensive Tests are not working.  I run flask DB-reboot.  Start the system.  Run the setup.sh, step1.sh, step2.sh, and then download-gradbook.sh and the tests fail.

Upon inspection it appears that the problem may be due to the Grade for Participation field being 0 for all records.

**Comment by profgrumpy** [comment]
sorry had to undo the assignment, @neverdue will be joining us back in fall but he is not on payroll with us at the moment.
