### ISSUE TITLE
Improving information displayed in modal for initial / revised scores.

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#7]
For initial score and revised score, in the grading page, add 2 columns in the modal.
End result should be something like: 

Question | **answer** | **check mark** | answer selected by student

The new columns are marked in bold. 
The first one should be the correct answer to the question, the second should be a check mark that shows whether the student got it right or not. Use the following for the checkmarks since we're using these icons already in other parts of the UI: 
https://icons.getbootstrap.com/icons/check-square/
https://icons.getbootstrap.com/icons/x-square/
(just suggestions, feel free to make it look better / color the icons)

**Comment by neverdue** [comment]
I went ahead and did this, pushing commit now! (56f32b896612f46b560f6787b41f77f3e6023f32)

**Comment by profgrumpy** [comment]
I think you updated the initial_scores but not the revised_scores :)
Re-close if I got that wrong, but I just went through a test on the DB and the revised scores seems to be as originally designed

**Comment by profgrumpy** [comment]
Forgot to add correct answer to revised score modal.
