### ISSUE TITLE
Bottstrap mix of version 5.1 and 4.5.0

### ISSUE THREAD

**Issue by dvitel** [cereal-lab/EvoPIE#72]
We should use one of them because they are not backward compatible. 
5.1 - does not depend on jquery, has other set of css classes
4.5 - depends on jquery 
Problem that could appear - existing code could depend on both of them now
Now, css is taken for 5.1 for grader view (for example) and js from 4.5
Careful investigation is required how change of css or js to one or other version could affect UI/app

**Comment by dvitel** [comment]
https://github.com/cereal-lab/EvoPIE/blob/fe23f10c819db490ab439e158bd3f799f6277703/evopie/templates/base.html#L6
https://github.com/cereal-lab/EvoPIE/blob/fe23f10c819db490ab439e158bd3f799f6277703/evopie/templates/base.html#L38-L40

**Comment by neverdue** [comment]
Created this branch for this issue: https://github.com/cereal-lab/EvoPIE/tree/72-bottstrap-mix-of-version-51-and-450
There are 3 separate issued addressing 3 sub-issues.

**Comment by neverdue** [comment]
Done! Merged to master!
