### ISSUE TITLE
Compact view of questions for student

### ISSUE THREAD

**Issue by dvitel** [cereal-lab/EvoPIE#75]
Collapse question cards and present answers in short form. 
Alternative: present one question at a time but devise more complex navigation between questions

**Comment by dvitel** [comment]
It would be better to present to student 1 question at a time. When questions go one after another + when there is animation of hiding textarea - UI jumps and confuses student by shown content shift. The flow could be: 
1. We show question with alternatives in one page
2. Near each non-selected option we have a button outlined red stating "Not explained" - button is aligned to the right of the alternative block text
3. On click we show a modal with textarea where student enters explanation and confirms. Then button changes to green outlines "Explained"
4. When student finish with question, there is Next button, which leads to page rerendering with next question data
5. There should be also navigation Back (no need for now I assume to support browser Back button - but would be nice)
6.  After last question there should be summary of all answers with quick navigation to question of concern

**Comment by neverdue** [comment]
Here is my proposed solution, you can access it at this branch https://github.com/cereal-lab/EvoPIE/tree/75-compact-view-of-questions-for-student

![CleanShot 2023-05-01 at 17 25 28@2x](https://user-images.githubusercontent.com/61725107/235534269-b7a9f535-4b0f-477b-9534-28a34748ce4b.png)

**Comment by profgrumpy** [comment]
@dvitel can you close this issue if we're done with it?
