### ISSUE TITLE
Compute "justifications score" based on likes

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#8]
In the quiz-grader page, add a column score that shows the points earned by each student based on how many likes from other students his or her justifications received. 

Formula for scoringjustifications

score(s) = sum { Likes(g,s) * min( ( **MaxLikes** * **LimitingFactor**) / LikesGiven(g) , 1 ) }

where

- **s** is the student whose justifications are being scored
- **g** is any student who gave a like to one of s' justifications
- **Likes(g,s)** is 1 if student g gave a like to a justification from student s
- **LikesGiven(g)** is the total # of likes given by student g
- **MaxLikes** is the number of all alternatives for all questions in this quiz * number of justifications from other students shown for each alternative.
- **LimitingFactor** is [0:1] and represents the maximal percentage of all justifications that the student could like, that is allowed for them to like. For instance, if there are 50 **MaxLikes** in a quiz but the **LimitingFactor** is .5 then every like that the student gives will be worth 1 point for the student that receives it except if the student gives more than 25 likes in which case the value of each individual like will decrease proportionally to how many likes they gave past **MaxLikes** * **LimitingFactor**.

All of the above are to be measured independently for each quiz.

**Comment by profgrumpy** [comment]
Please note that,  once we have the "justifications score" computed with the above formula, we still do not have a grade...

How do we translate the number of points received into a "justifications grade"?

Idea: assign grade to student as sum of likes on all their justifications, then compare to the sum of likes for all justifications of all other students. We give points based on how they rank compared to others as a percentage of likes they achieved compared to the student with most likes.

**Comment by profgrumpy** [comment]
Seems to be working fine but only way to be sure is to take off and nuke the entire site it from orbit. I mean, add tests to the Easy Labels Tests and compute by hand the expected results in terms of justifications grades so that we may check that it is working. 
Scenarios to consider:
- [ ] Justification does not get any like at all
- [ ] Justification gets 1 like only
- [ ] Justification gets the highest number of likes (set it high enough that we have clearly distinguished quartiles)
- [ ] 1 Justification gets enough to be in quartile 1, 2, 3, or 4 (one for each)

**Comment by neverdue** [comment]
Added a commit which pushed all scripts (85eb73129505be733e232b50e517c3b9a3cec3cf)
