### ISSUE TITLE
Migrate testing folder to Dmytro's flask CLI tests

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#81]
With the new flask CLI commands and their integration with PyTest, we can make the old "testing" folder obsolete and remove it. What's left to do is to migrate 2 out of the 3 tests from "extensive tests", along with their accompanying reference csv files to the new testing system.

**Comment by neverdue** [comment]
Migrated the remaining tests to pytest along with the csv files!
https://github.com/cereal-lab/EvoPIE/tree/81-migrate-testing-folder-to-dmytros-flask-cli-tests
